image: preetamjinka/ci:golang-2018-02

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"
          - go test ./... # test go
          - cd web && npm i && npm test # test web
          - cd "${PACKAGE_PATH}"
          - cd metadata && go build && cd ..
          - cd web && go build && cd ..
          - cd web && make all && npm run build && tar czvf assets.tar.gz static templates && cd ..
          - python s3_upload.py infinitynorm-builds-1 ./metadata/metadata "transverse_metadata_${BITBUCKET_COMMIT}"
          - python s3_upload.py infinitynorm-builds-1 ./web/web "transverse_web_${BITBUCKET_COMMIT}"
          - python s3_upload.py infinitynorm-builds-1 ./web/assets.tar.gz "transverse_assets_${BITBUCKET_COMMIT}.tar.gz"
