name: Master build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Docker build
        run: "docker build -t preetamjinka/transverse:$GITHUB_SHA -t preetamjinka/transverse:latest ."
      - name: Push image to Docker Hub
        run: "docker push preetamjinka/transverse:$GITHUB_SHA"
      - name: Push image to Docker Hub
        run: "docker push preetamjinka/transverse:latest"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/ansible
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
